files:

- name: foliant
  description: "demo of foliant, generator of random synthetic words"
  image: script.jpg

- name: projects
  description: software projects I'm running or have participated in

- name: thoughts
  description: "weblog: random thoughts scribbled hastily"
