language: node_js
node_js: node
script: yarn run build
cache: yarn
addons:
  apt:
    packages:
      - graphicsmagick
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  skip_cleanup: true  # keep created files
  local_dir: gh-pages
  on:
    branch: src
  target_branch: master
