package main

import (
	"go/format"

	"github.com/mitranim/gg"
	"github.com/mitranim/gg/grepr"
)

func init() { commands.Add(`games_steam`, cmdGamesSteam) }

func cmdGamesSteam() {
	/**
	Note: this file is expected to be created manually. At the time of writing,
	the JSON data can be found by visiting one's Steam profile webpage and
	copying it from one of the scripts inlined into HTML. TODO cleaner approach.
	Steam might have an API for this.
	*/
	src := ReadSteamGames(`misc/steam_apps.json`)

	var conf grepr.Conf
	conf.Indent = "\t"
	conf.Pkg = `main` // Doesn't work at the time of writing.

	gg.WriteFile(`misc/games_steam.go`, gg.Try1(format.Source(gg.ToBytes(`
package main

// AUTOGENERATED. DO NOT EDIT.

import "github.com/mitranim/gt"

var _ = `+grepr.StringC(conf, src)))))
}
