package main

import "github.com/mitranim/gt"

// Sketch, wildly incomplete.
func initSiteGames() []Game {
	return []Game{
		{
			Name:     `FTL: Faster Than Light`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/212680`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/212680/header.jpg`),
			Desc:     `One of the greatest roguelikes. Highly influential, and highly enjoyable. Start on Easy difficulty. One run ≈ 2-3 hours.`,
			TimeSink: TimeSinkSafe,
			Tags: Slice(
				TagPc, TagWindows, TagMac, TagConsole, TagMobile,
				Tag2d,
				TagSolo, TagPve,
				TagStrategy, TagTurnBased, TagSciFi, TagRoguelike, TagSpace,
			),
			IsListed: true,
		},
		{
			Name:     `Slay the Spire`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/646570`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/646570/header.jpg`),
			Desc:     `Strategic roguelike deck building dungeon crawler. One run ≈ 2-3 hours.`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagConsole, TagWindows, TagMac, TagMobile,
				Tag2d,
				TagSolo, TagPve,
				TagStrategy, TagDeckBuilder, TagRoguelike, TagTurnBased,
			),
			IsListed: true,
		},
		{
			Name:     `Beneath Oresa`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/1803400`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/1803400/header.jpg`),
			Desc:     `Strategic roguelike deck building dungeon crawler inspired by _Slay the Spire_. One run ≈ 2-3 hours.`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagStrategy, TagDeckBuilder, TagRoguelike, TagTurnBased,
			),
			IsListed: true,
		},
		{
			Name:     `Undertale`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/391540`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/391540/header.jpg`),
			Desc:     `Touching, uplifting story. _Highly_ recommended. Don't let pixel art deter you.`,
			TimeSink: TimeSinkSafe,
			Tags: Slice(
				TagPc, TagConsole, TagWindows, TagMac,
				Tag2d,
				TagSolo, TagPve,
				TagRolePlay, TagStory, TagFantasy, TagPacifist, TagPhilosophical,
			),
			IsListed: true,
		},
		{
			Name:     `Astroneer`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/361420`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/361420/header.jpg`),
			Desc:     `Planetary exploration, survival, resource gathering, building, terraforming.`,
			TimeSink: TimeSinkDanger,
			Tags: Slice(
				TagPc, TagConsole, TagWindows,
				Tag3d, TagThirdPerson,
				TagSolo, TagCoop, TagPve,
				TagCrafting, TagBuilding, TagExploration, TagSpace, TagSciFi, TagOpenWorld,
				TagGrind, TagPacifist,
			),
			IsListed: true,
		},
		{
			Name:     `Horizon Zero Dawn`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/1151640`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/header.jpg`),
			Desc:     `True masterpiece! Excellent game design, story, characters, dialogs, music, graphics, UI, and more!`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagConsole, TagWindows,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagOpenWorld, TagExploration, TagShooter, TagRolePlay, TagStory, TagSciFi,
				TagCrafting,
			),
			IsListed: true,
		},
		{
			Name:     `Subnautica`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/264710`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/264710/header.jpg`),
			Desc:     `Exploring, surviving, crafting, and building in an amazingly beautiful alien ocean. Doesn't hand-hold, tell you where to go, or what to do. Highly recommended!`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows, TagMac,
				Tag3d, TagFirstPerson,
				TagSolo, TagPve,
				TagSciFi, TagExploration, TagCrafting, TagBuilding, TagUnderwater, TagStory, TagPacifist,
			),
			IsListed: true,
		},
		{
			Name:     `Subnautica: Below Zero`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/848450`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/848450/header.jpg`),
			Desc:     `_Subnautica_'s expansion that became its own game. Slightly different environment and toys, but basically more of the same. Smaller than the original.`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows, TagMac,
				Tag3d, TagFirstPerson,
				TagSolo, TagPve,
				TagSciFi, TagExploration, TagCrafting, TagBuilding, TagUnderwater, TagStory, TagPacifist,
			),
			IsListed: true,
		},
		{
			Name:     `Divinity Original Sin 2`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/435150`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/435150/header.jpg`),
			Desc:     `Marvelous RPG with deep mechanics, amazing writing, characters, dialogs, story, music, and more. Check my [tips & tricks](/posts/divinity-original-sin-2)!`,
			TimeSink: TimeSinkDanger,
			Tags: Slice(
				TagPc, TagConsole, TagWindows,
				Tag3d, TagIsometric,
				TagSolo, TagCoop, TagPve,
				TagRolePlay, TagStory, TagFantasy,
				TagMagic, TagTurnBased, TagParty, TagCrafting,
			),
			IsListed: true,
		},
		{
			Name:     `Darkest Dungeon`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/262060`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/262060/header.jpg`),
			Desc:     `Turn-based, party-based dungeon crawler inspired by Lovecraftian horror stories, with fairly unique mechanics.`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows, TagMac, TagConsole, TagMobile,
				Tag2d,
				TagSolo, TagPve,
				TagStrategy, TagTurnBased, TagParty, TagFantasy,
			),
			IsListed: true,
		},
		{
			Name:     `Talos Principle`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/257510`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/257510/header.jpg`),
			Desc:     `Well-designed puzzle game with amazingly deep and thought-provoking monologues and dialogues. Excellent relaxing music. Take your time, play it slow, and _think_.`,
			TimeSink: TimeSinkSafe,
			Tags: Slice(
				TagPc, TagWindows, TagMac, TagConsole, TagMobile,
				Tag3d, TagFirstPerson, TagThirdPerson,
				TagSolo, TagPuzzle, TagSciFi, TagPacifist, TagPhilosophical,
			),
			IsListed: true,
		},
		{
			Name:     `Portal`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/400`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/400/header.jpg`),
			Desc:     `Highly influential and acclaimed puzzle game. Excellent in its minimalism. For added context, I recommend playing _Half-Life 2_ first; _Portal_ takes place in the same world, at the same time.`,
			TimeSink: TimeSinkSafe,
			Tags: Slice(
				TagPc, TagConsole, TagWindows,
				Tag3d, TagSolo,
				TagFirstPerson, TagPuzzle, TagSciFi, TagPacifist, TagPhilosophical,
			),
			IsListed: true,
		},
		{
			Name:     `Portal 2`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/620`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg`),
			Desc:     `Sequel to _Portal_, with more mechanics and a longer campaign.`,
			TimeSink: TimeSinkSafe,
			Tags: Slice(
				TagPc, TagConsole, TagWindows,
				Tag3d, TagFirstPerson,
				TagSolo, TagCoop,
				TagPuzzle, TagSciFi, TagPacifist,
			),
			IsListed: true,
		},
		{
			Name:     `Witcher 2: Assassins of Kings`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/20920`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/20920/header.jpg`),
			Desc:     `RPG following after the events of the original _Witcher_ books. Excellent writing, characters, dialogs, music. Requires unfucking, check [my recommendations](/posts/witcher).`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows, TagConsole,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagMelee, TagMagic, TagStory, TagRolePlay, TagFantasy, TagCrafting,
			),
			IsListed: true,
		},
		{
			Name:     `Witcher 3: Wild Hunt`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/292030`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg`),
			Desc:     `Legendary RPG beloved by all. Excellent writing, characters, dialogs, music, combat mechanics, and more, and it is **HUGE**. Requires unfucking, read [my recommendations](/posts/witcher).`,
			TimeSink: TimeSinkDanger,
			Tags: Slice(
				TagPc, TagWindows, TagConsole,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagMelee, TagMagic, TagStory, TagRolePlay, TagFantasy,
				TagOpenWorld, TagExploration, TagCrafting,
			),
			IsListed: true,
		},
		{
			Name:     `Mass Effect Trilogy (Legendary Edition)`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/1328670`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/1328670/header.jpg`),
			Desc:     `One of the greatest sci-fi RPG experiences ever made. Huge influence on other games and on many people's lives. Mechanics and graphics are outdated by modern standards, but the setting, characters, dialogs, story, music and more are timeless.`,
			TimeSink: TimeSinkDanger,
			Tags: Slice(
				TagPc, TagWindows, TagConsole,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagShooter, TagStory, TagRolePlay, TagSciFi, TagParty, TagMagic,
				TagExploration, TagSpace,
			),
			IsListed: true,
		},
		{
			Name:     `Mass Effect: Andromeda`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/1238000`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/1238000/header.jpg`),
			Desc:     `Worthy successor to previous ME titles. Excellent sci-fi RPG in its own right. Requires unfucking. Read [my recommendations](/posts/andromeda).`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows, TagConsole,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagShooter, TagStory, TagRolePlay, TagSciFi, TagParty, TagMagic,
				TagOpenWorld, TagExploration, TagSpace, TagCrafting,
			),
			IsListed: true,
		},
		{
			Name:     `Metal Gear Rising: Revengeance`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/235460`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/235460/header.jpg`),
			Desc:     `Badass melee slasher with cyborgs, vibroblades, giant robots, metal music, and some surprisingly thoughtful dialogs. Requires a gamepad.`,
			TimeSink: TimeSinkSafe,
			Tags: Slice(
				TagPc, TagWindows, TagConsole,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagMelee, TagSciFi, TagStory, TagPhilosophical,
			),
			IsListed: true,
		},
		{
			Name:     `NieR:Automata`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/524220`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/524220/header.jpg`),
			Desc:     `Surprisingly thought-provoking and touching. Brought me to tears. _Avoid external spoilers!_ Go for "true ending". Use original Japanese voiceovers and English subtitles. Requires unfucking via external tools, check [PCGW](https://www.pcgamingwiki.com/wiki/Nier_Automata). Requires a gamepad.`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows, TagConsole,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagMelee, TagShooter, TagSciFi, TagStory, TagPhilosophical,
			),
			IsListed: true,
		},
		{
			Name:     `Prey`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/480490`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/480490/header.jpg`),
			Desc:     `True successor to System Shock. Stealth gameplay on an abandoned space station infested by truly alien outsiders. Love the environments, gameplay, music. Thoughtful. See [PCGW](https://www.pcgamingwiki.com/wiki/Prey_\(2017\)) for tweaks and tools.`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows, TagConsole,
				Tag3d, TagFirstPerson,
				TagSolo, TagPve,
				TagShooter, TagSciFi, TagSpace, TagStory, TagPhilosophical,
			),
			IsListed: true,
		},
		{
			Name:     `Control`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/870780`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/870780/header.jpg`),
			Desc:     `Shooter / magic hybrid in a setting where all the paranormal sci-fi tropes are real. If you've read "Понедельник начинается в субботу", this may feel familiar.`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows, TagConsole,
				Tag3d, TagThirdPerson,
				TagSolo, TagPve,
				TagShooter, TagMagic, TagSciFi, TagStory, TagPhilosophical,
			),
			IsListed: true,
		},
		{
			Name:     `Warframe`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/230410`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg`),
			Desc:     `Third person shooter/melee hybrid with deep mechanics and a bewildering bevy of toys. Read [stupid headcanon](/posts/warframe-headcanon) authored by me and friends (spoilers!).`,
			TimeSink: TimeSinkExtreme,
			Tags: Slice(
				TagPc, TagConsole, TagWindows,
				Tag3d, TagThirdPerson,
				TagSolo, TagCoop, TagPve,
				TagShooter, TagMelee, TagCrafting, TagBuilding, TagGrind, TagSciFi,
			),
			IsListed: true,
		},
		{
			Name:     `No Man's Sky`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/275850`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg`),
			Desc:     `Exploring an open-world galaxy where everything is procedurally generated. Lots of features. Use a [save editor](https://github.com/zencq/NomNom) to minimize grinding.`,
			TimeSink: TimeSinkDanger,
			Tags: Slice(
				TagPc, TagConsole, TagWindows,
				Tag3d, TagFirstPerson, TagThirdPerson,
				TagSolo, TagCoop, TagPve,
				TagShooter, TagSciFi, TagSpace,
				TagOpenWorld, TagExploration, TagCrafting, TagBuilding, TagGrind,
			),
			IsListed: true,
		},
		{
			Name:     `Half-Life: Source`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/280`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/280/header.jpg`),
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows,
				Tag3d, TagFirstPerson,
				TagSolo, TagPve,
				TagShooter, TagStory,
			),
			IsListed: false,
		},
		{
			Name:     `Half-Life 2`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/220`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/220/header.jpg`),
			Desc:     `Highly influential first-person shooter with fluid on-the-fly story narration. Somewhat primitive by modern standards, but I still recommend this, especially if you plan to play _Portal_.`,
			TimeSink: TimeSinkModerate,
			Tags: Slice(
				TagPc, TagWindows,
				Tag3d, TagFirstPerson,
				TagSolo, TagPve,
				TagShooter, TagStory,
			),
			IsListed: true,
		},
		{
			Name:     `Half-Life 2: Episode One`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/380`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/380/header.jpg`),
			Desc:     `Continues the story of _Half-Life 2_.`,
			TimeSink: TimeSinkSafe,
			Tags: Slice(
				TagPc, TagWindows,
				Tag3d, TagFirstPerson,
				TagSolo, TagPve,
				TagShooter, TagStory,
			),
			IsListed: true,
		},
		{
			Name:     `Half-Life 2: Episode Two`,
			Link:     gt.ParseNullUrl(`https://store.steampowered.com/app/420`),
			Img:      gt.ParseNullUrl(`https://cdn.cloudflare.steamstatic.com/steam/apps/420/header.jpg`),
			Desc:     `Continues the story of _Half-Life 2: Episode One_. The story is left unfinished.`,
			TimeSink: TimeSinkSafe,
			Tags: Slice(
				TagPc, TagWindows,
				Tag3d, TagFirstPerson,
				TagSolo, TagPve,
				TagShooter, TagStory,
			),
			IsListed: true,
		},
	}
}
