files:

- name: foliant
  description: "demo of foliant, a generator of random synthetic words"
  js: true
  image: script.jpg
  echo:
  - name: foliant/index

- name: projects
  description: software projects I'm running or have participated in
  echo:
  - name: projects/index

- name: thoughts
  description: "blog: random thoughts scribbled hastily"
  echo:
  - name: thoughts/index
