ignore: index|shadow-dom-issues

files:

# - name:     shadow-dom-issues
#   title:    Shadow DOM Issues
#   image:    kenmainr-in-praise-of-shadows.jpg
#   date:     2015-03-n/a
#   echo:
#   - name: shadow-dom-issues/index

- name:     cheating-for-website-performance
  title:    Cheating For Website Performance
  image:    hexa.jpg
  date:     2015-03-11
  echo:
  - name: cheating-for-website-performance/index

- name:     keeping-things-simple
  title:    Keeping Things Simple
  image:    purple.jpg
  date:     2015-03-10
  echo:
  - name: keeping-things-simple/index

- name:     old-posts
  title:    Old Posts
  subtitle: some old stuff from around the net
  image:    typesets.jpg
  date:     really old
  echo:
  - name: old-posts/index
