[[pages]]
path = "index.html"
title = "about:mitranim"
description = "About me: bio, works, posts"

[[pages]]
path = "404.html"
title = "Page Not Found"

[[pages]]
path = "works.html"
title = "Works"
description = "Software I'm involved in"

[[pages]]
path = "posts.html"
title = "Blog Posts"
description = "Random notes and thoughts"

[[pages]]
path = "demos.html"
title = "Demos"
description = "Silly little demos"

[[pages]]
path = "resume.html"
title = "Resume"
description = "Nelo Mitranim's resume"
colorScheme = "color-scheme-light"

# ----

[[posts]]
path = "posts/warframe-headcanon.html"
inputPath = "posts/warframe-headcanon.md"
title = "Warframe Headcanon (Spoilers)"
description = "Collection of Warframe headcanon co-authored with friends"
created = 2020-06-16T05:27:55Z
isPublic = true
isListed = "dev"

[[posts]]
path = "posts/gameplay-conjecture.html"
inputPath = "posts/gameplay-conjecture.md"
title = "Gameplay Conjecture"
description = "Amount of gameplay ≈ amount of required decisions"
created = 2019-05-01T09:00:00Z
isPublic = "dev"
isListed = "dev"

[[posts]]
path = "posts/thoughts-on-the-egg.html"
inputPath = "posts/thoughts-on-the-egg.md"
title = "Thoughts on The Egg: a short story by Andy Weir, animated by Kurzgesagt"
description = ""
created = 2020-04-30T08:25:16Z
isPublic = true
isListed = true

[[posts]]
path = "posts/tips-and-tricks-doom-2016.html"
inputPath = "posts/tips-and-tricks-doom-2016.md"
title = "Tips and Tricks: Doom 2016"
description = "General tips, notes on difficulty, enemies, runes, weapons"
created = 2019-04-25T12:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/game-impressions-doom-2016.html"
inputPath = "posts/game-impressions-doom-2016.md"
title = "Game Impressions: Doom 2016"
description = "I really like Doom 2016, here's why"
created = 2019-04-25T11:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/astrotips.html"
inputPath = "posts/astrotips.md"
title = "Announcing Astrotips: Video Guides on Astroneer"
description = "A series of video guides, tips and tricks on Astroneer, an amazing space exploration and building game"
created = 2019-02-22T11:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/camel-case-abbr.html"
inputPath = "posts/camel-case-abbr.md"
title = "Don't Abbreviate in CamelCase"
description = 'CamelCase identifiers should avoid abbreviations, e.g. "JsonText" rather than "JSONText"'
created = 2019-01-17T07:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/remove-from-go.html"
inputPath = "posts/remove-from-go.md"
title = "Things I Would Remove From Go"
description = "If less is more, Go could gain by losing weight"
created = 2019-01-15T01:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/back-from-hiatus-2019.html"
inputPath = "posts/back-from-hiatus-2019.md"
title = "Back from Hiatus (2019)"
description = "Back to blogging after three and a half years"
created = 2019-01-15T00:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/cheating-for-performance-pjax.html"
inputPath = "posts/cheating-for-performance-pjax.md"
obsoletePath = "thoughts/cheating-for-performance-pjax.html"
title = "Cheating for Performance with Pjax"
description = "Faster page transitions, for free"
created = 2015-07-25T00:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/cheating-for-website-performance.html"
inputPath = "posts/cheating-for-website-performance.md"
obsoletePath = "thoughts/cheating-for-website-performance.html"
title = "Cheating for Website Performance"
description = "Frontend tips for speeding up websites"
created = 2015-03-11T00:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/keeping-things-simple.html"
inputPath = "posts/keeping-things-simple.md"
obsoletePath = "thoughts/keeping-things-simple.html"
title = "Keeping Things Simple"
description = "Musings on simplicity in programming"
created = 2015-03-10T00:00:00Z
isPublic = true
isListed = true

[[posts]]
path = "posts/next-generation-today.html"
inputPath = "posts/next-generation-today.md"
obsoletePath = "thoughts/next-generation-today.html"
title = "Next Generation Today"
description = "EcmaScript 2015/2016 workflow with current web frameworks"
created = 2015-05-18T00:00:00Z
isPublic = true
isListed = false

[[posts]]
path = "posts/old-posts.html"
inputPath = "posts/old-posts.md"
obsoletePath = "thoughts/old-posts.html"
title = "Old Posts"
description = "some old stuff from around the net"
created = 2015-01-01T00:00:00Z
isPublic = true
isListed = true
