[[pages]]
path = "index.html"
title = "about:mitranim"
description = "About me: bio, works, posts"

[[pages]]
path = "404.html"
title = "Page Not Found"

[[pages]]
path = "works.html"
title = "Works"
description = "Software I'm involved in"

[[pages]]
path = "posts.html"
title = "Blog Posts"
description = "Random notes and thoughts"

[[pages]]
path = "demos.html"
title = "Demos"
description = "Silly little demos"

[[pages]]
path = "resume.html"
title = "Resume"
description = "Nelo Mitranim's resume"
colorScheme = "color-scheme-light"

# ----

[[posts]]
path = "posts/spaces-tabs.html"
inputPath = "posts/spaces-tabs.md"
title = "Always Spaces, Never Tabs"
description = "Objective arguments that decided my personal preference"
publishedAt = 2020-10-23T06:48:15Z
isListed = true

[[posts]]
path = "posts/lisp-sexpr-hacks.html"
inputPath = "posts/lisp-sexpr-hacks.md"
title = "Hacks around S-expressions in Lisps"
description = "How far people are willing to go to get prefix and infix in a Lisp syntax"
publishedAt = 2020-10-21T06:34:24Z
isListed = true

[[posts]]
path = "posts/lang-var-minus.html"
inputPath = "posts/lang-var-minus.md"
title = "Language Design: Gotchas With Variadic Minus"
description = "Treating the minus operator as a function can be tricky and dangerous"
publishedAt = 2020-10-17T07:20:06Z
isListed = true

[[posts]]
path = "posts/lang-case-conventions.html"
inputPath = "posts/lang-case-conventions.md"
title = "Language Design: Case Conventions"
description = "Objective arguments to solve case conventions and move on"
publishedAt = 2020-10-16T15:30:41Z
isListed = true

[[posts]]
path = "posts/lang-homoiconic.html"
inputPath = "posts/lang-homoiconic.md"
title = "Language Design: Homoiconicity"
description = "Thoughts on homoiconicity, an interesting language quality seen in Lisps"
publishedAt = 2020-10-16T12:41:58Z
isListed = true

[[posts]]
path = "posts/warframe-headcanon.html"
inputPath = "posts/warframe-headcanon.md"
title = "Warframe Headcanon (Spoilers)"
description = "Collection of Warframe headcanon co-authored with friends"
publishedAt = 2020-10-10T12:25:32Z
isListed = true

[[posts]]
path = "posts/thoughts-on-the-egg.html"
inputPath = "posts/thoughts-on-the-egg.md"
title = "Thoughts on The Egg: a short story by Andy Weir, animated by Kurzgesagt"
description = ""
publishedAt = 2020-04-30T08:25:16Z
isListed = true

[[posts]]
path = "posts/gameplay-conjecture.html"
inputPath = "posts/gameplay-conjecture.md"
title = "Gameplay Conjecture"
description = "Amount of gameplay ≈ amount of required decisions"
isListed = "dev"

[[posts]]
path = "posts/tips-and-tricks-doom-2016.html"
inputPath = "posts/tips-and-tricks-doom-2016.md"
title = "Tips and Tricks: Doom 2016"
description = "General tips, notes on difficulty, enemies, runes, weapons"
publishedAt = 2019-04-25T12:00:00Z
isListed = true

[[posts]]
path = "posts/game-impressions-doom-2016.html"
inputPath = "posts/game-impressions-doom-2016.md"
title = "Game Impressions: Doom 2016"
description = "I really like Doom 2016, here's why"
publishedAt = 2019-04-25T11:00:00Z
isListed = true

[[posts]]
path = "posts/astrotips.html"
inputPath = "posts/astrotips.md"
title = "Announcing Astrotips: Video Guides on Astroneer"
description = "A series of video guides, tips and tricks on Astroneer, an amazing space exploration and building game"
publishedAt = 2019-02-22T11:00:00Z
isListed = true

[[posts]]
path = "posts/camel-case-abbr.html"
inputPath = "posts/camel-case-abbr.md"
title = "Don't Abbreviate in CamelCase"
description = 'CamelCase identifiers should avoid abbreviations, e.g. "JsonText" rather than "JSONText"'
publishedAt = 2019-01-17T07:00:00Z
isListed = true

[[posts]]
path = "posts/remove-from-go.html"
inputPath = "posts/remove-from-go.md"
title = "Things I Would Remove From Go"
description = "If less is more, Go could gain by losing weight"
publishedAt = 2019-01-15T01:00:00Z
isListed = true

[[posts]]
path = "posts/back-from-hiatus-2019.html"
inputPath = "posts/back-from-hiatus-2019.md"
title = "Back from Hiatus (2019)"
description = "Back to blogging after three and a half years"
publishedAt = 2019-01-15T00:00:00Z
isListed = true

[[posts]]
path = "posts/cheating-for-performance-pjax.html"
inputPath = "posts/cheating-for-performance-pjax.md"
obsoletePath = "thoughts/cheating-for-performance-pjax.html"
title = "Cheating for Performance with Pjax"
description = "Faster page transitions, for free"
publishedAt = 2015-07-25T00:00:00Z
isListed = true

[[posts]]
path = "posts/cheating-for-website-performance.html"
inputPath = "posts/cheating-for-website-performance.md"
obsoletePath = "thoughts/cheating-for-website-performance.html"
title = "Cheating for Website Performance"
description = "Frontend tips for speeding up websites"
publishedAt = 2015-03-11T00:00:00Z
isListed = true

[[posts]]
path = "posts/keeping-things-simple.html"
inputPath = "posts/keeping-things-simple.md"
obsoletePath = "thoughts/keeping-things-simple.html"
title = "Keeping Things Simple"
description = "Musings on simplicity in programming"
publishedAt = 2015-03-10T00:00:00Z
isListed = true

[[posts]]
path = "posts/next-generation-today.html"
inputPath = "posts/next-generation-today.md"
obsoletePath = "thoughts/next-generation-today.html"
title = "Next Generation Today"
description = "EcmaScript 2015/2016 workflow with current web frameworks"
publishedAt = 2015-05-18T00:00:00Z
isListed = false

[[posts]]
path = "posts/old-posts.html"
inputPath = "posts/old-posts.md"
obsoletePath = "thoughts/old-posts.html"
title = "Old Posts"
description = "some old stuff from around the net"
publishedAt = 2015-01-01T00:00:00Z
isListed = true
