ignore: index|next-gen-custom-elements

files:

# - name:     next-gen-custom-elements
#   title:    'Next-gen Today Part 2: Custom Elements'
#   description: 'Borrowing component ideas from Angular 2, Aurelia, and Polymer'
#   image:    schema.jpg
#   date:     2015-05-n/a
#   echo:
#   - name: next-gen-custom-elements/index

- name:     next-generation-today
  title:    Next Generation Today
  description: Next-gen workflow with current web frameworks
  image:    cloud-city.jpg
  date:     2015-05-18
  echo:
  - name: next-generation-today/index

- name:     cheating-for-website-performance
  title:    Cheating For Website Performance
  image:    hexa.jpg
  date:     2015-03-11
  echo:
  - name: cheating-for-website-performance/index

- name:     keeping-things-simple
  title:    Keeping Things Simple
  image:    purple.jpg
  date:     2015-03-10
  echo:
  - name: keeping-things-simple/index

- name:     old-posts
  title:    Old Posts
  description: some old stuff from around the net
  image:    typesets.jpg
  date:     really old
  echo:
  - name: old-posts/index
