ignore: index|next-gen-custom-elements

files:

# - name:     next-gen-custom-elements
#   title:    'Next-gen Today Part 2: Custom Elements'
#   description: 'Borrowing component ideas from Angular 2, Aurelia, and Polymer'
#   image:    schema.jpg
#   date:     n/a
#   echo:
#   - name: next-gen-custom-elements/index

- name:     cheating-for-performance-pjax
  title:    "Cheating for Performance: Pjax"
  description: "Faster page transitions, for free"
  image:    strato.jpg
  date:     2015-07-25

- name:     next-generation-today
  title:    Next Generation Today
  description: EcmaScript 2015/2016 workflow with current web frameworks
  image:    cloud-city.jpg
  date:     2015-05-18

- name:     cheating-for-website-performance
  title:    Cheating For Website Performance
  description: Frontend tips for speeding up websites
  image:    hexa.jpg
  date:     2015-03-11

- name:     keeping-things-simple
  title:    Keeping Things Simple
  image:    purple.jpg
  date:     2015-03-10

- name:     old-posts
  title:    Old Posts
  description: some old stuff from around the net
  image:    typesets.jpg
  date:     really old
