backend:
  name: github
  repo: mitranim/mitranim.github.io
  branch: src

media_folder: cms/static/uploads
public_folder: uploads

collections:
  - name: pages
    label: Pages
    format: frontmatter
    delete: false
    files:
      - file: src/templates/index.mdx
        name: index
        label: Landing Page
        fields:
          - {name: papyre, widget: hidden}
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: string}
